# Generated by Django 6.0.1 on 2026-01-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('seller', models.CharField(max_length=255, verbose_name='Vendedor')),
                ('client', models.CharField(max_length=255, verbose_name='Cliente')),
                ('ci_ruc', models.CharField(max_length=20, verbose_name='CI/RUC')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='IVA Aplicado (%)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Producto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='P. Unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ticket.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Detalle del Ticket',
                'verbose_name_plural': 'Detalles del Ticket',
            },
        ),
    ]
