# Generated by Django 6.0.1 on 2026-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendedor'),
        ),
    ]
