# Generated by Django 6.0.1 on 2026-01-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
    ]
