# Generated by Django 6.0.1 on 2026-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='iva_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='IVA Aplicado (%)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='P. Unitario'),
        ),
    ]
