# Generated by Django 6.0.1 on 2026-01-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_total_alter_ticketdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='total',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=15, verbose_name='P. Unitario'),
        ),
    ]
