# Generated by Django 6.0.1 on 2026-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Compañía')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('sri_access_key', models.CharField(max_length=255, verbose_name='Clave de Acceso SRI')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Porcentaje de IVA')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
    ]
