# Generated by Django 6.0.1 on 2026-01-14 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_name',
            field=models.CharField(default='Universidad Estatal de Milagro', max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='company',
            name='client_ruc',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='RUC del Cliente'),
            preserve_default=False,
        ),
    ]
